"""Finite persisted Phase 5 state vocabulary."""

from enum import StrEnum


class AgentStatus(StrEnum):
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    RETRIEVING = "RETRIEVING"
    ASSESSING = "ASSESSING"
    SEARCHING = "SEARCHING"
    CRAWLING = "CRAWLING"
    INDEXING = "INDEXING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"


class GapStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    ABANDONED = "ABANDONED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"


class ActionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StopReason(StrEnum):
    SUFFICIENT_EVIDENCE = "SUFFICIENT_EVIDENCE"
    MAX_ITERATIONS = "MAX_ITERATIONS"
    QUERY_BUDGET = "QUERY_BUDGET"
    SEED_BUDGET = "SEED_BUDGET"
    PAGE_BUDGET = "PAGE_BUDGET"
    TIME_BUDGET = "TIME_BUDGET"
    CANCELLED = "CANCELLED"
    STAGNATION = "STAGNATION"
    NO_ACTIONABLE_GAPS = "NO_ACTIONABLE_GAPS"
    INDEX_INCONSISTENT = "INDEX_INCONSISTENT"
    ERROR = "ERROR"


class GapPriority(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
